spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN}
app.auth.family-username=${APP_FAMILY_USERNAME}
app.auth.family-password=${APP_FAMILY_PASSWORD}
app.auth.signup-enabled=${APP_SIGNUP_ENABLED:false}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
server.servlet.session.cookie.secure=true
app.storage.mode=${APP_STORAGE_MODE:s3}
