CREATE TABLE IF NOT EXISTS invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    email VARCHAR(254) NOT NULL,
    role VARCHAR(30) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,
    invited_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invitations_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    CONSTRAINT fk_invitations_invited_by FOREIGN KEY (invited_by) REFERENCES users(id),
    CONSTRAINT chk_invitations_role CHECK (role IN ('ADMIN', 'MANAGER', 'STAFF', 'ACCOUNTANT', 'VIEWER'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_invitations_token_hash
    ON invitations(token_hash);

CREATE INDEX IF NOT EXISTS idx_invitations_workspace_email
    ON invitations(workspace_id, email);
