ALTER TABLE purchases ALTER COLUMN rate TYPE NUMERIC(19, 2);
ALTER TABLE purchases ALTER COLUMN amount TYPE NUMERIC(19, 2);
ALTER TABLE sales ALTER COLUMN rate TYPE NUMERIC(19, 2);
ALTER TABLE sales ALTER COLUMN amount TYPE NUMERIC(19, 2);

ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

UPDATE company_profiles SET version = 0 WHERE version IS NULL;
UPDATE customers SET version = 0 WHERE version IS NULL;
UPDATE suppliers SET version = 0 WHERE version IS NULL;
UPDATE purchases SET version = 0 WHERE version IS NULL;
UPDATE sales SET version = 0 WHERE version IS NULL;

ALTER TABLE company_profiles ALTER COLUMN version SET NOT NULL;
ALTER TABLE customers ALTER COLUMN version SET NOT NULL;
ALTER TABLE suppliers ALTER COLUMN version SET NOT NULL;
ALTER TABLE purchases ALTER COLUMN version SET NOT NULL;
ALTER TABLE sales ALTER COLUMN version SET NOT NULL;
