CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    actor_username VARCHAR(254),
    method VARCHAR(10) NOT NULL,
    path VARCHAR(300) NOT NULL,
    status_code INT NOT NULL,
    ip_address VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_events_company FOREIGN KEY (company_id) REFERENCES company_profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_events_company_created
    ON audit_events(company_id, created_at DESC);
