CREATE TABLE IF NOT EXISTS saved_taka_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    taka_no INT NOT NULL,
    meters DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_taka_entries_company FOREIGN KEY (company_id) REFERENCES company_profiles(id),
    CONSTRAINT uq_saved_taka_entries_company_number UNIQUE (company_id, taka_no)
);

CREATE INDEX IF NOT EXISTS idx_saved_taka_entries_company_number
    ON saved_taka_entries (company_id, taka_no);
