CREATE TABLE IF NOT EXISTS saved_taka_entry_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_taka_batches_company FOREIGN KEY (company_id) REFERENCES company_profiles(id),
    CONSTRAINT uq_saved_taka_batches_company_key UNIQUE (company_id, idempotency_key)
);

ALTER TABLE saved_taka_entries ADD COLUMN IF NOT EXISTS batch_id BIGINT;
ALTER TABLE saved_taka_entries
    ADD CONSTRAINT fk_saved_taka_entries_batch FOREIGN KEY (batch_id) REFERENCES saved_taka_entry_batches(id);

CREATE INDEX IF NOT EXISTS idx_saved_taka_entries_batch ON saved_taka_entries (batch_id);
