CREATE TABLE IF NOT EXISTS email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_type VARCHAR(40) NOT NULL,
    recipient VARCHAR(254) NOT NULL,
    token VARCHAR(200) NOT NULL,
    workspace_name VARCHAR(254),
    role VARCHAR(40),
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at TIMESTAMP,
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email_outbox_due
    ON email_outbox(status, next_attempt_at, id);
