CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_workspaces_slug ON workspaces(slug);

CREATE TABLE IF NOT EXISTS workspace_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    CONSTRAINT fk_workspace_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_members_workspace_user
    ON workspace_members(workspace_id, user_id);

CREATE INDEX IF NOT EXISTS idx_workspace_members_user
    ON workspace_members(user_id);

ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS workspace_id BIGINT;

INSERT INTO workspaces (name, slug, status)
SELECT 'Devashish Business Group', 'devashish-business-group', 'ACTIVE'
WHERE NOT EXISTS (
    SELECT 1 FROM workspaces WHERE slug = 'devashish-business-group'
);

UPDATE company_profiles
SET workspace_id = (
    SELECT id FROM workspaces WHERE slug = 'devashish-business-group'
)
WHERE workspace_id IS NULL;

ALTER TABLE company_profiles ALTER COLUMN workspace_id SET NOT NULL;

ALTER TABLE company_profiles
    ADD CONSTRAINT fk_company_profiles_workspace
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id);

DROP INDEX IF EXISTS uk_company_profiles_trade_name;
CREATE UNIQUE INDEX IF NOT EXISTS uk_company_profiles_workspace_trade_name
    ON company_profiles(workspace_id, trade_name);

INSERT INTO workspace_members (workspace_id, user_id, role)
SELECT w.id, u.id, 'OWNER'
FROM workspaces w
JOIN users u ON 1 = 1
WHERE w.slug = 'devashish-business-group'
  AND NOT EXISTS (
      SELECT 1
      FROM workspace_members existing_member
      WHERE existing_member.workspace_id = w.id
        AND existing_member.user_id = u.id
  );

ALTER TABLE workspace_members
    ADD CONSTRAINT chk_workspace_members_role
    CHECK (role IN ('OWNER', 'ADMIN', 'MANAGER', 'STAFF', 'ACCOUNTANT', 'VIEWER'));
